/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 drone.glb -T --shadows
Author: Helindu (https://sketchfab.com/Helindu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/autopilot-aircraft-drone-c7ed0e884b2a4850b53a85c03802a3d3
Title: autopilot aircraft / drone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/drone/drone-transformed.glb");
  return (
    <group dispose={null} scale={0.1} position={[-50, 7, 0]}>
      <group
        position={[500.65, -50.63, -18.61]}
        rotation={[-Math.PI / 2, 0.2, 1]}
        scale={2}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material011_0.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material011_0_1.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material013_0.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material010_0.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Material012_0.geometry}
          material={materials["Material.012"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/drone/drone-transformed.glb");
